FROM node:20-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
ARG VITE_SITE_NAME=Sign UP Jeetwin
ENV VITE_SITE_NAME=$VITE_SITE_NAME
ARG VITE_BRAND_NAME=Sign UP Jeetwin
ENV VITE_BRAND_NAME=$VITE_BRAND_NAME
RUN npm run build

FROM nginx:alpine
COPY nginx.public.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
