FROM node:20-alpine AS build
WORKDIR /app

ARG VITE_SITE_NAME=Sign UP Jeetwin
ENV VITE_SITE_NAME=$VITE_SITE_NAME

ARG VITE_BRAND_NAME=Sign UP Jeetwin
ENV VITE_BRAND_NAME=$VITE_BRAND_NAME

ARG VITE_APP_MODE=all
ENV VITE_APP_MODE=$VITE_APP_MODE

ARG VITE_BASE=/
ENV VITE_BASE=$VITE_BASE

COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npm run build:admin

FROM nginx:alpine
COPY nginx.admin.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
