import React, { useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import Shell from "../components/Shell";
import TextField from "../components/TextField";
import Button from "../components/Button";
import Toast, { type ToastState } from "../components/Toast";
import { resetPassword } from "../api";
import { resolveErrorMessage } from "../utils/errors";

function hasLetterAndNumber(v: string): boolean {
  return /[A-Za-z]/.test(v) && /\d/.test(v);
}

export default function ResetPasswordPage() {
  const [params] = useSearchParams();
  const token = params.get("token") ?? "";

  const [pw, setPw] = useState("");
  const [pw2, setPw2] = useState("");
  const [show, setShow] = useState(false);
  const [show2, setShow2] = useState(false);
  const [toast, setToast] = useState<ToastState>({ kind: "idle" });
  const [loading, setLoading] = useState(false);

  const err = useMemo(() => {
    if (!token) return "Missing token";
    if (pw.trim().length < 8) return "Min 8 characters";
    if (!hasLetterAndNumber(pw)) return "Include 1 letter and 1 number";
    if (pw2 !== pw) return "Passwords do not match";
    return null;
  }, [token, pw, pw2]);

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setToast({ kind: "idle" });
    if (err) {
      setToast({ kind: "err", msg: err });
      return;
    }
    setLoading(true);
    try {
      await resetPassword({ token, newPassword: pw });
      setToast({ kind: "ok", msg: "Password updated!" });
      setPw("");
      setPw2("");
    } catch (err) {
      setToast({ kind: "err", msg: resolveErrorMessage(err, "Failed to update password") });
    } finally {
      setLoading(false);
    }
  }

  return (
    <Shell
      title="Reset password"
      subtitle="Use the one-time link generated by admin (valid ~15 minutes)."
      leftBadge="Reset • One-time • Secure"
    >
      <div className="cardXL">
        <div className="cardHead">
          <div>
            <div className="cardTitle">Set new password</div>
            <div className="cardSub">Min 8 chars, include 1 letter and 1 number.</div>
          </div>
        </div>

        <form onSubmit={onSubmit} className="formGrid">
          <TextField
            label="New password"
            type={show ? "text" : "password"}
            value={pw}
            onChange={setPw}
            right={
              <button className="miniBtn" type="button" onClick={() => setShow((s) => !s)}>
                {show ? "Hide" : "Show"}
              </button>
            }
          />
          <TextField
            label="Confirm password"
            type={show2 ? "text" : "password"}
            value={pw2}
            onChange={setPw2}
            right={
              <button className="miniBtn" type="button" onClick={() => setShow2((s) => !s)}>
                {show2 ? "Hide" : "Show"}
              </button>
            }
          />

          <Button type="submit" disabled={loading || !!err}>
            {loading ? "Updating..." : "Update password"}
          </Button>

          {!token ? <div className="finePrint">Invalid link: token missing.</div> : null}
        </form>
      </div>

      <Toast toast={toast} onClear={() => setToast({ kind: "idle" })} />
    </Shell>
  );
}
